<?php

/**
 * @file
 * Provides integration with the Gutenberg editor.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityFormBuilder;
use Drupal\gutenberg\Render\Element;

/**
 * Implements hook_form_alter().
 */
function gutenberg_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_type_edit_form') {
    $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');

    $form['gutenberg'] = array(
      '#type' => 'details',
      '#title' => t('Gutenberg experience'),
      '#description' => t(''),
      '#group' => 'additional_settings',
      '#weight' => 999,
      'enable_gutenberg_experience' => array(
        '#type' => 'checkbox',
        '#title' => t('Enable Gutenberg experience'),
        '#description' => t('If node has a long text field with Gutenberg text format, the edit form will turn into a full Gutenberg UI experience.'),
        '#default_value' => $config->get($form['type']['#default_value'] . '_enable_full')
      )
    );

    $form['actions']['submit']['#submit'][] = '_gutenberg_node_form_submit';
  }
}

/**
 * Implements hook_form_node_form_alter().
 */
function gutenberg_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = $form_state->getFormObject()->getEntity();
  $node_type = $node->type->getString();

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  $text_fields = array();

  // Iterate over all node fields and apply gutenberg text format
  // on first text field found.
  $field_names = array_keys($node->getFields());

  foreach ($field_names as $key => $value) {
    $field = $node
    ->getFieldDefinition($value)
    ->getFieldStorageDefinition()
    ->getPropertyDefinitions();

    $field_properties = array_keys($node
      ->getFieldDefinition($value)
      ->getFieldStorageDefinition()
      ->getPropertyDefinitions());

    if (in_array('format', $field_properties)) {
      $text_fields[] = $value;
    }
  }

  // foreach ($field_names as $key => $value) {
  //   if (isset($form[$value]) && isset($form[$value]['widget'])) {
  //     $form[$value]['widget']['#theme'] .= '__gutenberg';
  //   }
  // }

  // No point going forward when no text fields on the form.
  if (count($text_fields) === 0) {
    return;
  }

  if ($gutenberg_enabled) {
    $form[$text_fields[0]]['widget'][0]['#format'] = 'gutenberg';
    $form[$text_fields[0]]['#attributes']['class'][] = 'field--gutenberg';
  }

  foreach($text_fields as $fieldname) {
    // For the rest of the text fields call after build to remove
    // Gutenberg from text format options.
    if ($gutenberg_enabled) {
      if ($text_fields[0] !== $fieldname) {
        $form[$fieldname]['widget']['#after_build'][] = 'gutenberg_form_node_form_after_build';
      }
    }
    else {
      $form[$fieldname]['widget']['#after_build'][] = 'gutenberg_form_node_form_after_build';
    }
  }

  // Let's "import" Seven admin theme changes on node edit form.
  $form['#theme'] = ['node_edit_form'];
  $form['#attached']['library'][] = 'seven/node-form';

  $form['advanced']['#type'] = 'container';
  $form['meta']['#type'] = 'container';
  $form['meta']['#access'] = TRUE;
  $form['meta']['changed']['#wrapper_attributes']['class'][] = 'container-inline';
  $form['meta']['author']['#wrapper_attributes']['class'][] = 'container-inline';

  $form['revision_information']['#type'] = 'container';
  $form['revision_information']['#group'] = 'meta';
  // <-- Seven theme changes

  // Let's move the remaining fields to a "special"
  // form group that can be used later by JS to move to
  // Gutenberg's sidebar.
  $form['additional_fields'] = array(
    '#type' => 'container',
    '#access' => TRUE,
    '#title' => t('Additional Fields'),
    '#weight' => 99,
  );

  // Move status to Published/meta pane.
  $form['status']['#group'] = 'meta';

  $excluded_fields = array(
    'status',
    'title',
    'uid',
    'created',
    'changed',
    'promote',
    'sticky',
    'path',
    'comment',
    'revision_log'
  );

  foreach ($field_names as $key => $value) {
    if (
      array_key_exists($value, $form)
      && $value !== $text_fields[0]
      && !in_array($value, $excluded_fields)
    ){
      $form[$value]['#group'] = 'additional_fields';
    }

    // if (array_key_exists($value, $form)) {
    //   var_dump($form[$value]['#type']);
    // }
  }

  $form['test'] = array(
    // '#type' => 'textfield',
    '#type' => 'textfield_gutenberg',
    '#title' => t('Test'),
    '#default_value' => 'Placeholder...',
    '#group' => 'additional_fields',
    '#theme' => 'input__textfield__gutenberg',
  );

  $form['test2'] = array(
    '#type' => 'textfield',
    '#title' => t('Test 2'),
    '#default_value' => 'Placeholder 2...',
    '#group' => 'additional_fields',
  );
}

/**
 * Called by after build text fields on the form.
 */
function gutenberg_form_node_form_after_build(array $element, FormStateInterface $form_state) {
  unset($element[0]['format']['format']['#options']['gutenberg']);
  return $element;
}

function _gutenberg_node_form_submit(array $form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $config->set($form_state->getValue('type') . '_enable_full', $form_state->getValue('enable_gutenberg_experience'))->save();
}

/**
 * Implements template_preprocess_field().
 */
function gutenberg_preprocess_node(&$variables) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = $variables['elements']['#node'];
  $node_type = $node->type->getString();

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  if ($gutenberg_enabled) {
    $variables['#attached']['library'][] = 'gutenberg/frontkom-gutenberg-frontend';
  }
}

function gutenberg_preprocess_input(&$variables) {
  $element =& $variables['element'];

  $variables['directory'] = 'modules/gutenberg';
  $element['element']['#theme'] = 'input__textfield__gutenberg';
  $element['element']['#value_callback'] = 'Drupal\\gutenberg\\Render\\Element\\TextfieldGutenberg';
  var_dump($variables);
}

// function gutenberg_preprocess_form_element(&$variables) {
//   $variables['element']['#theme'] = 'input__textfield__gutenberg';
//   var_dump($variables['element']['#theme']);
// }

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function gutenberg_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    $route_match = \Drupal::service('current_route_match');
    if (!$route_match->getParameter('node_type')) {
      return;
    }
    $node_type = $route_match->getParameter('node_type')->get('type');
  }
  else {
    $node_type = $node->type->getString();
  }

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  if ($gutenberg_enabled) {
    if ($hook === 'page') {
      if (in_array('page__node__edit', $suggestions)) {
        $suggestions = ['page__node__edit__gutenberg'];
      }
  
      if (in_array('page__node__add', $suggestions)) {
        $suggestions = ['page__node__add__gutenberg'];
      }
    }

    if ($hook === 'node_edit_form') {
      $suggestions = ['node_edit_form__gutenberg'];
    }

    if ($hook === 'container') {
      $suggestions = ['container__gutenberg'];
    }

    if ($hook === 'input') {
      $suggestions = ['input__gutenberg'];
      if ($variables['theme_hook_original'] === 'input__textfield') {
        $suggestions[] = 'input__textfield__gutenberg';
      }
      // $suggestions = ['input__textfield__gutenberg'];
    }

    if ($hook === 'form_control') {
      $suggestions = ['form_control__gutenberg'];
    }

    if ($hook === 'form_element') {
      $suggestions = ['form_element__gutenberg'];
    }

    if ($hook === 'form_element_label') {
      $suggestions = ['form_element_label__gutenberg'];
    }

    if ($hook === 'field_multiple_value_form') {
      $suggestions = ['field_multiple_value_form__gutenberg'];
    }
  }
}

/**
 * Implements hook_theme().
 */
function gutenberg_theme() {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('gutenberg')->getPath();

  return array(
    'page__node__edit__gutenberg' => array(
      'template' => 'page--node--edit--gutenberg',
      'path' => $path . '/templates',
    ),
    'page__node__add__gutenberg' => array(
      'template' => 'page--node--add--gutenberg',
      'path' => $path . '/templates',
    ),
    'node_edit_form__gutenberg' => array(
      'template' => 'node-edit-form--gutenberg',
      'path' => $path . '/templates',
    ),
    'details__gutenberg' => array(
      'template' => 'details--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'details'
    ),
    'container__gutenberg' => array(
      'template' => 'container--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'container'
    ),
    'input__gutenberg' => array(
      'template' => 'input--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'input'
    ),
    'input__textfield__gutenberg' => array(
      'template' => 'input--textfield--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'input__textfield'
    ),
    'form_element__gutenberg' => array(
      'template' => 'form-element--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'form_element'
    ),
    'form_element_label__gutenberg' => array(
      'template' => 'form-element-label--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'form_element_label'
    ),
    'form_control__gutenberg' => array(
      'template' => 'form-control--gutenberg',
      'path' => $path . '/templates',
      'base hook' => 'form_control'
    ),

  );
}
