<?php

/**
 * @file
 * Provides integration with the Gutenberg editor.
 */

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\EntityFormBuilder;
use Drupal\node\NodeInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_form_alter().
 */
function gutenberg_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_type_edit_form') {
    $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');

    $form['gutenberg'] = array(
      '#type' => 'details',
      '#title' => t('Gutenberg experience'),
      '#description' => t(''),
      '#group' => 'additional_settings',
      '#weight' => 999,
      'enable_gutenberg_experience' => array(
        '#type' => 'checkbox',
        '#title' => t('Enable Gutenberg experience'),
        '#description' => t('If node has a long text field with Gutenberg text format, the edit form will turn into a full Gutenberg UI experience.'),
        '#default_value' => $config->get($form['type']['#default_value'] . '_enable_full')
      )
    );

    $form['actions']['submit']['#submit'][] = '_gutenberg_node_form_submit';
  }
}

/**
 * Implements hook_form_node_form_alter().
 */
function gutenberg_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = $form_state->getFormObject()->getEntity();
  $node_type = $node->type->getString();

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  $text_fields = array();

  // Iterate over all node fields and apply gutenberg text format
  // on first text field found.
  $field_names = array_keys($node->getFields());

  foreach ($field_names as $key => $value) {
    $field = $node
    ->getFieldDefinition($value)
    ->getFieldStorageDefinition()
    ->getPropertyDefinitions();

    $field_properties = array_keys($node
      ->getFieldDefinition($value)
      ->getFieldStorageDefinition()
      ->getPropertyDefinitions());

    if (in_array('format', $field_properties)) {
      $text_fields[] = $value;
    }
  }

  // No point going forward when no text fields on the form.
  if (count($text_fields) === 0) {
    return;
  }

  if ($gutenberg_enabled) {
    $form[$text_fields[0]]['widget'][0]['#format'] = 'gutenberg';
    $form[$text_fields[0]]['#attributes']['class'][] = 'field--gutenberg';
  }

  // TODO: Need to solve form validation with react components.
  if (!$node->nid->getString()) {
    $form['title']['widget'][0]['value']['#default_value'] = t('New page');
  }

  foreach($text_fields as $fieldname) {
    // For the rest of the text fields call after build to remove
    // Gutenberg from text format options.
    if ($gutenberg_enabled) {
      if ($text_fields[0] !== $fieldname) {
        $form[$fieldname]['widget']['#after_build'][] = 'gutenberg_form_node_form_after_build';
      }
    }
    else {
      $form[$fieldname]['widget']['#after_build'][] = 'gutenberg_form_node_form_after_build';
    }
  }

  // Let's move the remaining fields to a "special"
  // form group that can be used lated by JS to move to
  // Gutenberg's sidebar.
  $form['additional_fields'] = array(
    '#type' => 'container',
    '#access' => TRUE,
    '#title' => t('Additional Fields'),
    '#weight' => 99,
  );

  // Move status to Published/meta pane.
  $form['status']['#group'] = 'meta';

  $excluded_fields = array(
    'status',
    'title',
    'uid',
    'created',
    'changed',
    'promote',
    'sticky',
    'path',
    'comment',
    'revision_log'
  );

  foreach ($field_names as $key => $value) {
    if (
      array_key_exists($value, $form)
      && $value !== $text_fields[0]
      && !in_array($value, $excluded_fields)
    ){
      $form[$value]['#group'] = 'additional_fields';
    }
  }
}

/**
 * Called by after build text fields on the form.
 */
function gutenberg_form_node_form_after_build(array $element, FormStateInterface $form_state) {
  unset($element[0]['format']['format']['#options']['gutenberg']);
  return $element;
}

function _gutenberg_node_form_submit(array $form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $config->set($form_state->getValue('type') . '_enable_full', $form_state->getValue('enable_gutenberg_experience'))->save();
}

/**
 * Implements template_preprocess_field().
 */
function gutenberg_preprocess_node(&$variables) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = $variables['elements']['#node'];
  $node_type = $node->type->getString();

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  if ($gutenberg_enabled) {
    $variables['#attached']['library'][] = 'gutenberg/frontend';
  }

  // if($variables['element']['#field_type'] === 'text_with_summary') {
  //   $element = $variables['element'];
  //   dsm($element);
  // }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function gutenberg_theme_suggestions_node_edit_form_alter(array &$suggestions, array $variables) {
  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    $route_match = \Drupal::service('current_route_match');
    if (!$route_match->getParameter('node_type')) {
      return;
    }
    $node_type = $route_match->getParameter('node_type')->get('type');
  }
  else {
    $node_type = $node->type->getString();
  }

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  if ($gutenberg_enabled) {
    $suggestions = ['node_edit_form__gutenberg'];
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function gutenberg_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if (!in_array('page__node__edit', $suggestions)
      && !in_array('page__node__add', $suggestions)) {
    return;
  }

  $config = \Drupal::service('config.factory')->getEditable('gutenberg.settings');
  $node = \Drupal::routeMatch()->getParameter('node');

  if (!$node) {
    $route_match = \Drupal::service('current_route_match');
    if (!$route_match->getParameter('node_type')) {
      return;
    }
    $node_type = $route_match->getParameter('node_type')->get('type');
  }
  else {
    $node_type = $node->type->getString();
  }

  $gutenberg_enabled = $config->get($node_type . '_enable_full');

  if ($gutenberg_enabled) {
    if (in_array('page__node__edit', $suggestions)) {
      $suggestions = ['page__node__edit__gutenberg'];
    }

    if (in_array('page__node__add', $suggestions)) {
      $suggestions = ['page__node__add__gutenberg'];
    }
  }
}

/**
 * Implements hook_theme().
 */
function gutenberg_theme() {
  return array(
    'page__node__edit__gutenberg' => array(
      'template' => 'page--node--edit--gutenberg',
    ),
    'page__node__add__gutenberg' => array(
      'template' => 'page--node--add--gutenberg',
    ),
    'node_edit_form__gutenberg' => array(
      'template' => 'node-edit-form--gutenberg',
    )
  );
}

/**
 * Implements hook_element_info_alter().
 */
function gutenberg_element_info_alter(array &$info) {
  if (!empty($info['text_format'])) {
    // Add custom processor to eliminate the format if needed.
    $info['text_format']['#process'][] = '_gutenberg_text_format_processor';
  }
}

/**
 * Process the text format element to eliminate the gutenberg format.
 *
 * On the fields that don't belong to content types with enabled gutenberg
 * experience there is no need to have the gutenberg format.
 *
 * @param array $element
 *   Render Element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state object.
 * @param array $complete_form
 *   Complete form array.
 *
 * @return array
 *   Processed render element.
 */
function _gutenberg_text_format_processor($element, FormStateInterface $form_state, array &$complete_form) {
  // Check first if the format is in the list. It might be disabled or the
  // current user has not rights to access it.
  if (!empty($element['format']) && isset($element['format']['format']['#options']['gutenberg'])) {
    // By default let's assume that gutenberg format is not allowed.
    $gutenberg_allowed = FALSE;
    /** @var \Drupal\Core\Entity\ContentEntityForm $form */
    $form = $form_state->getFormObject();
    // Check whether the form that contains the element is an EntityForm.
    if ($form instanceof EntityFormInterface) {
      // Get the entity from the form object for further processing.
      $entity = $form->getEntity();
      // Check whether entity is of node type, because currently only them are
      // supported.
      if ($entity instanceof NodeInterface) {
        // Get the node type to get the Gutenberg experience setting.
        $node_type = $entity->bundle();
        /** @var \Drupal\Core\Config\Config $config */
        $config = \Drupal::service('config.factory')
          ->getEditable('gutenberg.settings');
        $gutenberg_enabled = $config->get($node_type . '_enable_full');
        if (!empty($gutenberg_enabled)) {
          // Gutenberg experience is enabled for current content type and
          // the current user is allowed to use the format.
          $gutenberg_allowed = TRUE;
        }
      }
    }
    // If Gutenberg experience is not enabled for the current form or
    // current user is not allowed to use the format, disable the choice of
    // Gutenberg format for this element.
    if (!$gutenberg_allowed) {
      unset($element['format']['format']['#options']['gutenberg']);
    }
  }
  return $element;
}

/**
 * Implements hook_views_pre_render().
 */
function gutenberg_views_pre_render(ViewExecutable $view) {
  if ($view->id() == "reusable_blocks" && $view->current_display == 'page_1') {
    // Attached Gutenberg's basic style to reusable blocks view.
    $view->element['#attached']['library'][] = 'gutenberg/frontend';
    $view->element['#attached']['library'][] = 'gutenberg/admin';
  }
}
